name: CI
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.4-openjdk-17
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Git Version
        id: version
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/' || startsWith(github.ref, 'refs/heads/feature/add-automated-semver')
        uses: codacy/git-version@2.7.1


      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}

      #get githubflow version
      - name: Update version
        #only in master and release branches
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')
        run: mvn -B versions:set -DnewVersion=${{ steps.version.outputs.version }} -DgenerateBackupPoms=false

      - name: Build and Unit test
        run: mvn -ntp -e clean test

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /root/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: ${{ runner.os }}-docker

      - name: Package
        run: mvn -ntp -e package

      - name: Publish
        run: mvn -ntp -e -Djkube.docker.username=${{ secrets.DOCKER_USERNAME }} -Djkube.docker.password=${{ secrets.DOCKER_PASSWORD }} k8s:push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')


